### PR TITLE
Port away from glib

### PR DESCRIPTION
**Pull request by sandsmark**
replaces the glib event loop with a custom qt one, and replaces the other glib stuff with some nicer qt stuff.

there's still some "leftovers" that should be removed, there's a lot of ugly glib code patterns left, but this is a start at least.

### CODE REVIEW

**Comment by sandsmark** [comment]
So, in addition to just porting it to the Qt event loop, I also did an astyle run to make it more compliant with the Qt code style, did a run with clang-tidy and clazy to clean up some minor issues, and fixed some other minor issues.

**Comment by tsujan** [comment]
Closing this not just because of merge conflicts but because, as it was said explicitly in https://github.com/lxqt/pavucontrol-qt/pull/43, we won't port away from GLib.

**Comment by sandsmark** [comment]
fwiw, the merge conflicts were trivial, fixed them now.

and it's not really porting away from glib, it's instead integrating properly with qt (and the pulseaudio qt event loop wrapper is much cleaner than the glib event loop integration, imho).

**Comment by sandsmark** [comment]
also fwiw: I also cleaned up the code a fair bit, added back e. g. the volume preview "ding" sound, etc.

**Comment by tsujan** [comment]
@sandsmark 
It was decided 2 years ago. I didn't participate in the discussion but agree with the decision because, when pavucontrol-qt works well as it is, there's no good reason to make heavy code changes, which might introduce new bugs and give us unnecessary headaches.

If another LXQt dev had time to review this amount of changes and make sure that it wouldn't add bugs, he would review this -- actually, since the changes are heavy, 2 devs were needed, at least.

**Comment by tsujan** [comment]
And forking is always possible.

**Pull request closed without merging**
