### PR TITLE
WIP: Try to make sure Qt uses a glib event loop

### PR DESCRIPTION
**Pull request by sandsmark**

### CODE REVIEW

**Comment by palinek** [comment]
Please, be more verbose about this one.

Why should pavucontrol-qt force this on its own?

**Comment by sandsmark** [comment]
because it explicitly uses the glib event loop some lines under this:
`src/pavucontrol.cc:    pa_glib_mainloop *m = pa_glib_mainloop_new(g_main_context_default());`

I started porting it to using the normal Qt event loop, but this is the easiest fix/

**Comment by Kaffeine** [comment]
Oh yes, if someone decided to (on purpose) disable glib event loop, lets... unconditionally ruin that in C++ code. :-)

This change leads to confusion and only hides the real issue. Someone set "QT_NO_GLIB" and want to see how the system works. Everything work fine and the one would say: "Hey, my Qt-based system is working without glib!" but it will not be the truth.

Please either let a user to see the problem (so someone can come in and fix it) or properly port the app.

**Comment by PCMan** [comment]
The glib main loop is required by pulse audio client.
There is nothing wrong with it.
Why there is always desire to kill glib even when it works without problems?

**Comment by Kaffeine** [comment]
I agree with all your points (the app needs glib event loop and it is OK), but it is just wrong to ignore/suppress an explicitly set behaviour control variable.

I would suggest to replace the unsetenv by a print of a critical or fatal message (something like the first line in the message from @PCMan) if QT_NO_GLIB environment variable is set.
Instant return of a nonzero exit code is also an option.

The variable is mostly useful for a developer e.g to simplify multithread application analysis/debugging.

**Comment by PCMan** [comment]
@Kaffeine This makes sense. I agree with the rationale. But I'm not sure how many people will read the console debug message if they fail to start an GUI app.
However, I believe that normal users should not set QT_NO_GLIB. So I agree with you. :)

**Comment by agaida** [comment]
@Kaffeine @PCMan - Full ACK

**Comment by sandsmark** [comment]
I've run my full system with QT_NO_GLIB for a very long time without any issues (except for pavucontrol-qt), and I know it's not that uncommon.

glib is pretty buggy, e. g. the glib event loop chokes when you restart its timers too quickly (probably a race condition). and because its code is pretty convoluted I gave up trying to debug it a long time ago and just disabled it globally.

**Comment by PCMan** [comment]
@sandsmark Well, glib itself is very solid, stable, and well-tested. It's Qt's glib event loop integration that's actually buggy. If you emit Qt signals in glib signal handlers, it will have no effect. :-(

**Comment by agaida** [comment]
et all the unset don't make much sense. Closing this

**Comment by sandsmark** [comment]
Just in case someone wants to pick up the porting to the qt main loop some day, here's the branch I apparently started on: https://github.com/sandsmark/pavucontrol-qt/tree/martin/qtmainloop

**Comment by sandsmark** [comment]
... and just because I wondered how hard it would be, I finished it and cleaned out the rest of the glib stuff.

**Pull request closed without merging**
