### PR TITLE
Standardize desktop file

### PR DESCRIPTION
**Pull request by isf63**
Update src/translations/pavucontrol-qt.desktop.yaml

https://github.com/lxqt/lxqt-notificationd/pull/387

### CODE REVIEW

**Comment by tsujan** [comment]
IMO this is good. @stefonarch?

**Comment by tsujan** [comment]
You may also want to add Qt to `GenericName`, like. "Qt GUI for Controlling PulseAudio Volume".

"Pipewire" may not be needed because it's covered automatically.

**Comment by stefonarch** [comment]
Adding _Qt Gui_ is good IMO. Not sure about mentioning pipewire, afaik pulseaudio is outdated on most systems but I never understood much of pulseaudio/pipewire.

**Comment by isf63** [comment]
Done.

**Review by tsujan — APPROVED** [review]
Thanks

**Pull request merged**
