### PR TITLE
Code modernization

### PR DESCRIPTION
**Pull request by shlyakpavel**
Hello
I have updated and simplified source code with the features provided by modern c++ standarts.
I really hope you enjoy it
Have a nice day)

### CODE REVIEW

**Comment by agaida** [comment]
@palinek - it would be nice if you find the time for a review - if good i want the PR in the release

**Comment by agaida** [comment]
@palinek - will throw it to a pbuilder and test it before merging

**Comment by shlyakpavel** [comment]
I am terribly sorry, I have done some mess on master. I am not that good in git yet...

**Comment by agaida** [comment]
@shlyakpavel - don't worry, git take some time, right now the mess was only in your master

**Comment by shlyakpavel** [comment]
I have tried to go for range-based loops, but I'm not sure it is a good idea
Can you please check it out? https://github.com/shlyakpavel/pavucontrol-qt/commit/2f40adc4ed59cd433425cfe1685522eb67c975ec

**Comment by agaida** [comment]
@palinek  - your help is needed again, can't review it, non of the needed knowledge available :)

**Comment by agaida** [comment]
apply, build and runs fine - GTM

**Pull request merged**
