### PR TITLE
Updated *.ts files

### PR DESCRIPTION
**Pull request by stefonarch**

### CODE REVIEW

**Comment by stefonarch** [comment]
@tsujan Sure this cannot be merged now, but what can we do about later?

**Comment by tsujan** [comment]
> Sure this cannot be merged now

Sorry, I don't remember the source. What's the problem?

**Comment by tsujan** [comment]
Oh, a string is changed from plain-text to rich text. Am I right? If so, it should be translated again; I don't think we can keep the old translations by manually editing them (not knowing which is which in Chinese, for example).

**Comment by tsujan** [comment]
If you made the PR by applying `lxqt-transupdate`, why did you close it? I'd trust Qt.

**Comment by stefonarch** [comment]
I just think it's better to keep the translations in 1.2.0

**Comment by tsujan** [comment]
They won't be kept; Qt will ignore them.

**Comment by stefonarch** [comment]
Looks like only `<br>` is inserted, so it wouldn't be difficult to add it back to translations. I never saw that message in all the time.

**Comment by tsujan** [comment]
OK.

**Pull request closed without merging**
